import { DuckDBInstance } from '@duckdb/node-api';
import { mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import { config } from './config.js';
export async function generate() {
 await mkdir(dirname(config.dbPath), { recursive: true });
 const db = await DuckDBInstance.create(config.dbPath); const c = await db.connect();
 const seed = config.seed; const d = config.asOf;
 // SCALE multiplies every table (SCALE=250 -> 1M servers, 6M findings, 2.5M incidents, 4M backups) to test
 // the agent on enterprise-sized data. Default 1 keeps the reproducible 58k-row evaluation dataset.
 const scale = Math.max(1, Number(process.env.SCALE || 1));
 const S = 4000*scale, V = 24000*scale, I = 10000*scale, B = 16000*scale, A = 80*Math.min(scale,50);
 const W = Math.max(5, String(S).length), AW = Math.max(3, String(A).length);
 if (!/^\d{4}-\d{2}-\d{2}$/.test(d) || !Number.isInteger(seed)) throw new Error('Invalid seed/date');
 await c.run(`CREATE OR REPLACE TABLE dataset_info AS SELECT ${seed} seed, DATE '${d}' as_of, 'Synthetic enterprise estate; no real company data' description`);
 await c.run(`CREATE OR REPLACE TABLE estates AS SELECT 'EST-'||i estate_id, ['Americas','Europe','Asia Pacific','Shared Services'][i] estate_name, ['US','GB','IN','DE'][i] headquarters_country, ['Infrastructure','Operations','Technology','Platforms'][i] owner_team, 'Active' status FROM range(1,5) t(i)`);
 await c.run(`CREATE OR REPLACE TABLE applications AS SELECT 'APP-'||lpad(i::VARCHAR,${AW},'0') application_id, ['Payments','Inventory','Customer Portal','Risk Engine','Data Platform','HR Suite','Logistics','Identity'][1+(i-1)%8]||' '||i application_name, 'EST-'||(1+(i-1)%4) estate_id, ['Finance','Retail','Operations','Corporate'][1+(i-1)%4] business_unit, ['Tier 1','Tier 2','Tier 3'][1+(i-1)%3] criticality, 'team-'||i "owner", 'owner'||i||'@example.test' owner_email, ['Gold','Silver','Bronze'][1+(i-1)%3] service_tier, ['Internal','Customer','Partner'][1+(i-1)%3] customer_type, 'Active' lifecycle_state, 'Local POC application '||i description, 'cost-'||i cost_center, 'repo/app-'||i repository, '4.'||(i%10)||'.0' "version", 'quarterly' release_cadence, (i%3=0) regulated, '99.9%' availability_target, 240 rto_minutes, 60 rpo_minutes, DATE '${d}'-500 created_date, DATE '${d}'-i::INTEGER updated_date FROM range(1,${A+1}) t(i)`);
 await c.run(`CREATE OR REPLACE TABLE servers AS WITH base AS (SELECT i, (hash(i+${seed})%9223372036854775807)::BIGINT h FROM range(1,${S+1}) t(i)) SELECT 'SRV-'||lpad(i::VARCHAR,${W},'0') server_id, 'host-'||lpad(i::VARCHAR,${W},'0') hostname, 'APP-'||lpad((1+h%${A})::VARCHAR,${AW},'0') application_id, ['Production','Development','Test','Staging'][1+(h//80)%4] environment, ['US','GB','IN','DE','JP','AU'][1+(h//320)%6] country, ['Americas','Europe','Asia Pacific'][1+(h//1920)%3] region, ['Red Hat Enterprise Linux','Ubuntu','Windows Server','SUSE Linux'][1+(h//5760)%4] os, ['7','8','9','10'][1+(h//23040)%4] os_version, ['Running','Stopped','Maintenance'][1+(h//92160)%3] server_state, 'platform-team-'||(1+h%12) "owner", ['Supported','Unsupported','Extended'][1+(h//276480)%3] support_status, ['Active','Retiring','Planned'][1+(h//829440)%3] lifecycle_state, ['Finance','Retail','Operations','Corporate'][1+(h//2488320)%4] business_unit, '10.'||(h%250)||'.'||(i//250)||'.'||(1+i%249) ip_address, ['aws','azure','on-prem'][1+(h//9953280)%3] platform, (2*(1+h%16)) cpu_cores, (4*(1+h%32)) memory_gb, (100*(1+h%20)) disk_gb, ['London','Virginia','Mumbai','Frankfurt'][1+(h//29859840)%4] datacenter, (h%2=0) virtualized, 'zone-'||(1+h%3) availability_zone, 'daily' backup_policy, 'monthly' patch_schedule, 'CC-'||(100+h%50) cost_center, DATE '${d}'-(100+h%1800)::INTEGER created_date, DATE '${d}'-(h%120)::INTEGER last_patch_date, TIMESTAMP '${d} 09:00:00'-(h%24)::INTEGER*INTERVAL '1 hour' last_seen, DATE '${d}'-(h%30)::INTEGER updated_date FROM base`);
 await c.run(`CREATE OR REPLACE TABLE vulnerabilities AS WITH base AS (SELECT i, (hash(i+${seed}+100000)%9223372036854775807)::BIGINT h FROM range(1,${V+1}) t(i)) SELECT 'VUL-'||i vulnerability_id, 'SRV-'||lpad((1+h%${S})::VARCHAR,${W},'0') server_id, 'CVE-2025-'||(1000+h%8000) cve, ['Critical','High','Medium','Low'][1+(h//4000)%4] severity, round((h%100)/10.0,1) cvss_score, ['Open','Remediated','Accepted'][1+(h//16000)%3] status, ['openssl','kernel','java','nginx','dotnet'][1+(h//48000)%5] package_name, '1.'||(h%20) affected_version, '2.'||(h%20) fixed_version, 'scanner-'||(1+h%3) "source", (h%5=0) exploit_available, (h%7=0) internet_exposed, 'security-team-'||(1+h%8) "owner", DATE '${d}'-(1+h%150)::INTEGER discovered_date, DATE '${d}'-(h%10)::INTEGER last_seen_date, DATE '${d}'+(h%30)::INTEGER due_date, CASE WHEN (h//16000)%3=1 THEN DATE '${d}'-(h%20)::INTEGER ELSE NULL END resolved_date, ['Patch','Upgrade','Mitigate'][1+h%3] remediation, 'finding-'||i title, 'Synthetic package finding '||i description, (h%9=0) exception_approved, 'scan-'||(h%100) scan_id FROM base`);
 await c.run(`CREATE OR REPLACE TABLE incidents AS WITH base AS (SELECT i, (hash(i+${seed}+200000)%9223372036854775807)::BIGINT h FROM range(1,${I+1}) t(i)) SELECT 'INC-'||i incident_id, 'SRV-'||lpad((1+h%${S})::VARCHAR,${W},'0') server_id, 'Synthetic service incident '||i title, ['Open','Investigating','Resolved','Closed'][1+(h//4000)%4] status, ['P1','P2','P3','P4'][1+(h//16000)%4] priority, ['Critical','High','Medium','Low'][1+(h//64000)%4] severity, ['Availability','Performance','Security','Backup'][1+(h//256000)%4] category, 'Service degradation detected' description, 'ops-'||(1+h%10) assigned_team, 'engineer-'||(h%20) assigned_to, TIMESTAMP '${d} 12:00:00'-(h%120)::INTEGER*INTERVAL '1 day' created_date, CASE WHEN (h//4000)%4>=2 THEN TIMESTAMP '${d} 12:00:00'-(h%120)::INTEGER*INTERVAL '1 day'+INTERVAL '3 hours' ELSE NULL END resolved_date, DATE '${d}'-(h%10)::INTEGER updated_date, (h%300)::INTEGER downtime_minutes, (h%2=0) customer_impact, (h%11=0) sla_breached, ['Configuration','Capacity','Dependency','Unknown'][1+h%4] root_cause, 'monitoring' detection_source, 'CHG-'||(h%200) change_id, (h%8=0) major_incident, 'ticket-'||i external_reference FROM base`);
 await c.run(`CREATE OR REPLACE TABLE backups AS WITH base AS (SELECT i, (hash(i+${seed}+300000)%9223372036854775807)::BIGINT h FROM range(1,${B+1}) t(i)) SELECT 'BKP-'||i backup_id, 'SRV-'||lpad((1+h%${S})::VARCHAR,${W},'0') server_id, ['Success','Failed','Partial','Running'][1+(h//4000)%4] status, ['Full','Incremental','Snapshot'][1+(h//16000)%3] backup_type, TIMESTAMP '${d} 08:00:00'-(h%30)::INTEGER*INTERVAL '1 day' started_at, TIMESTAMP '${d} 09:00:00'-(h%30)::INTEGER*INTERVAL '1 day' completed_at, TIMESTAMP '${d} 09:00:00'-(h%30)::INTEGER*INTERVAL '1 day' last_backup, 'daily' "policy", 30 retention_days, (10+h%500)::INTEGER size_gb, (5+h%120)::INTEGER duration_minutes, (h%2=0) "encrypted", ['Local','Object Storage','Tape'][1+h%3] destination, CASE WHEN (h//4000)%4=1 THEN 'BKP_TIMEOUT' ELSE NULL END error_code, CASE WHEN (h//4000)%4=1 THEN 'Backup exceeded time window' ELSE NULL END error_message, 'backup-team' "owner", ['Passed','Failed','Not tested'][1+h%3] restore_test_status, DATE '${d}'-(h%90)::INTEGER restore_test_date, 'job-'||(h%${S}) job_id, (h%4=0) "immutable", DATE '${d}'-(h%30)::INTEGER created_date FROM base`);
 await c.run(`CREATE OR REPLACE TABLE evergreening AS SELECT 'EVG-'||row_number() OVER () evergreen_id, server_id, ['Not started','In progress','Completed','Blocked'][1+(hash(server_id,${seed})%9223372036854775807)::BIGINT%4] evergreen_status, os current_os, os_version current_version, CASE WHEN os='Windows Server' THEN 'Windows Server 2025' ELSE os END upgrade_target, 'Latest supported release' target_version, DATE '${d}'+((hash(server_id)%9223372036854775807)::BIGINT%180)::INTEGER target_date, CASE WHEN (hash(server_id,${seed})%9223372036854775807)::BIGINT%4=2 THEN DATE '${d}'-((hash(server_id)%9223372036854775807)::BIGINT%60)::INTEGER ELSE NULL END completed_date, "owner", 'wave-'||(1+(hash(server_id)%9223372036854775807)::BIGINT%12) migration_wave, 'CHG-'||((hash(server_id)%9223372036854775807)::BIGINT%200) change_id, ['Low','Medium','High'][1+(hash(server_id)%9223372036854775807)::BIGINT%3] risk_level, 'Standard lifecycle refresh' reason, support_status, ((hash(server_id)%9223372036854775807)::BIGINT%5=0) blocker, CASE WHEN (hash(server_id)%9223372036854775807)::BIGINT%5=0 THEN 'Application certification pending' ELSE NULL END blocker_reason, 240 estimated_minutes, ((hash(server_id)%9223372036854775807)::BIGINT%10000)::INTEGER estimated_cost, 'Pending' approval_status, DATE '${d}'-200 created_date, DATE '${d}'-((hash(server_id)%9223372036854775807)::BIGINT%14)::INTEGER updated_date FROM servers`);
 for (const [table,description] of Object.entries({servers:'Server inventory. One row per server; server_id is unique. environment is deployment stage, support_status is OS vendor support.',applications:'Application registry. One row per application.',estates:'Organizational estate groups; join applications.estate_id.',vulnerabilities:'Security findings. Many per server. Active vulnerabilities have status Open. Critical is severity, not priority.',incidents:'Service incidents. Many per server. Recent means last 30 days unless specified. This month uses dataset as_of.',backups:'Backup run history, many per server. Latest backup: row_number ordered by started_at descending, backup_id descending.',evergreening:'OS upgrade lifecycle, one row per server.',dataset_info:'Deterministic synthetic dataset seed and reference date. Relative dates use as_of, not machine clock.'})) await c.run(`COMMENT ON TABLE ${table} IS '${description.replaceAll("'","''")}'`);
 c.closeSync(); db.closeSync(); console.log(`Generated ${config.dbPath}: scale ${scale} (${(S+V+I+B+A+4+S).toLocaleString('en-US')} rows); seed ${seed}; as of ${d}`);
}
if (process.argv[1]?.endsWith('generate.ts')) await generate();
