import { z } from 'zod';
export const stepSchema = z.object({id:z.string().max(32),objective:z.string().max(250),tool:z.enum(['inspect_schema','inspect_values','inspect_table','run_sql']),inputs:z.object({query:z.string().optional(),table:z.string().optional(),column:z.string().optional(),sql:z.string().optional()}),dependencies:z.array(z.string())});
export const planSchema = z.object({intent:z.string().max(300),clarification:z.string().max(300),steps:z.array(stepSchema).max(4)}).refine(p=>p.steps.length===0||p.steps.some(s=>s.tool==='run_sql'),{message:'A data plan must include at least one run_sql tool. inspect_table and inspect_values do not answer data requests.'});
export type Step = z.infer<typeof stepSchema>;
export type Plan = z.infer<typeof planSchema>;
export type Row = Record<string,unknown>;
export type Evidence = {stepId:string;objective:string;tool:string;sql?:string;rows:Row[];rowCount:number;truncated:boolean;totalRows?:number;durationMs:number;error?:string;repairs:number;queryPlan?:unknown;valueWarnings?:{column:string;literal:string;table:string;knownValues:unknown[];inspectionSql:string}[];warnings?:string[]};
// Compact memory of one answered turn; the last few are kept for follow-ups.
export type TurnMemory = {question:string;standalone:string;sql:string[];summary:string;entityKey?:string;entityTable?:string;ids:string[];literals:string[]};
export type State = {lastQuestion:string;intent:string;selectedIds:string[];previousSql:string[];filters:string[];timeRange:string;concepts:string[];schemaVersion?:number;turns?:TurnMemory[]};
export type Trace = {model?:string;sourceRevision?:number;schemaVersion?:number;operationOutline?:unknown;checklist?:{id:string;objective:string;dependencies:string[];status:'pending'|'running'|'verified'|'failed';error?:string}[];deadlineMs?:number;dataQuestion?:string;recordSummary?:boolean;question:string;intent:string;schema:unknown;plans:Plan[];observations?:unknown[];events:{message:string;at:number;phase?:string}[];evidence:Evidence[];llm:{purpose:string;durationMs:number;error?:string;thinking?:boolean;tokens?:number;promptTokens?:number}[];profile?:unknown;driver?:string;grounding?:unknown;standalone?:string;candidates?:unknown[];answerCheck?:unknown;answerSource?:string;retries:number;totalMs:number;error?:string};
export type Answer = {sessionId:string;status:'answered'|'incomplete'|'clarification'|'unavailable';text:string;evidence:Evidence[];presentation?:'table'|'records'|'metrics';trace:Trace;state:State};
