// 150-question stress set written after all harness changes: random phrasing, slang and typos,
// long join chains across every table, NULL semantics, edge cases and multi-turn conversations.
// Never imported by backend code. Oracles are independent SQL; checks are column-name independent.
import type {BatteryCase} from './battery-cases.js';
const c=(id:string,category:string,turns:string|string[],check:BatteryCase['check'],oracle?:string|string[],values?:(string|number)[]):BatteryCase=>({id,split:'fresh',category,turns:Array.isArray(turns)?turns:[turns],check,oracle,values});
const AS_OF="(SELECT as_of FROM dataset_info)";
const JOIN_EST="JOIN servers s USING(server_id) JOIN applications a USING(application_id) JOIN estates e USING(estate_id)";
export const battery150:BatteryCase[]=[
 // ---- casual, slang, typos ----
 c('t01','casual','yo how many boxes we got in prod rn','scalar',"SELECT count(*) FROM servers WHERE environment='Production'"),
 c('t02','casual','# of vulns thats critcal','scalar',"SELECT count(*) FROM vulnerabilities WHERE severity='Critical'"),
 c('t03','casual','incidnets this month?','scalar',`SELECT count(*) FROM incidents WHERE created_date>=date_trunc('month',${AS_OF}) AND created_date<date_trunc('month',${AS_OF})+INTERVAL 1 MONTH`),
 c('t04','casual','total ram across ubuntu hosts','scalar',"SELECT sum(memory_gb) FROM servers WHERE os='Ubuntu'"),
 c('t05','casual','any servers in australia?','scalar',"SELECT count(*) FROM servers WHERE country='AU'"),
 c('t06','casual','plz count backups that failed','scalar',"SELECT count(*) FROM backups WHERE status='Failed'"),
 c('t07','casual','whats the avg cvss','scalar','SELECT avg(cvss_score) FROM vulnerabilities'),
 c('t08','casual','how many apps r tier 3','scalar',"SELECT count(*) FROM applications WHERE criticality='Tier 3'"),
 c('t09','casual','SERVERS IN INDIA','scalar',"SELECT count(*) FROM servers WHERE country='IN'"),
 c('t10','casual','how many incidents r still open','scalar',"SELECT count(*) FROM incidents WHERE status='Open'"),
 c('t11','casual','count of redhat boxes in staging','scalar',"SELECT count(*) FROM servers WHERE os='Red Hat Enterprise Linux' AND environment='Staging'"),
 c('t12','casual','number of backups wich are encrypted','scalar','SELECT count(*) FROM backups WHERE encrypted'),
 c('t13','casual','how many vulnerabilites have an exploit','scalar','SELECT count(*) FROM vulnerabilities WHERE exploit_available'),
 c('t14','casual','windows machines that are stopped','scalar',"SELECT count(*) FROM servers WHERE os='Windows Server' AND server_state='Stopped'"),
 c('t15','casual','how many servers on prem','scalar',"SELECT count(*) FROM servers WHERE platform='on-prem'"),
 // ---- estate chains ----
 c('e01','estate-chain','how many servers does the Americas estate have','scalar',"SELECT count(*) FROM servers s JOIN applications a USING(application_id) JOIN estates e USING(estate_id) WHERE e.estate_name='Americas'"),
 c('e02','estate-chain','open critical vulnerabilities per estate','rows',`SELECT e.estate_name,count(*) FROM vulnerabilities v ${JOIN_EST} WHERE v.status='Open' AND v.severity='Critical' GROUP BY 1`),
 c('e03','estate-chain','failed backups by estate','rows',`SELECT e.estate_name,count(*) FROM backups b ${JOIN_EST} WHERE b.status='Failed' GROUP BY 1`),
 c('e04','estate-chain','how many P1 incidents in the Shared Services estate','scalar',`SELECT count(*) FROM incidents i ${JOIN_EST} WHERE i.priority='P1' AND e.estate_name='Shared Services'`),
 c('e05','estate-chain','blocked OS upgrades per estate','rows',`SELECT e.estate_name,count(*) FROM evergreening g ${JOIN_EST} WHERE g.evergreen_status='Blocked' GROUP BY 1`),
 c('e06','estate-chain','which estate has the most open vulnerabilities','contains',undefined,['Asia Pacific']),
 c('e07','estate-chain','average cvss of open findings in the Europe estate','scalar',`SELECT avg(v.cvss_score) FROM vulnerabilities v ${JOIN_EST} WHERE v.status='Open' AND e.estate_name='Europe'`),
 c('e08','estate-chain','total downtime minutes per estate','rows',`SELECT e.estate_name,sum(i.downtime_minutes) FROM incidents i ${JOIN_EST} GROUP BY 1`),
 c('e09','estate-chain','how many applications are in the Asia Pacific estate','scalar',"SELECT count(*) FROM applications a JOIN estates e USING(estate_id) WHERE e.estate_name='Asia Pacific'"),
 c('e10','estate-chain','production servers per estate','rows',"SELECT e.estate_name,count(*) FROM servers s JOIN applications a USING(application_id) JOIN estates e USING(estate_id) WHERE s.environment='Production' GROUP BY 1"),
 c('e11','estate-chain','SLA breaches in the Americas estate','scalar',`SELECT count(*) FROM incidents i ${JOIN_EST} WHERE i.sla_breached AND e.estate_name='Americas'`),
 c('e12','estate-chain','which estate has the fewest servers','contains',undefined,['Shared Services']),
 c('e13','estate-chain','how many unsupported servers does the Europe estate have','scalar',"SELECT count(*) FROM servers s JOIN applications a USING(application_id) JOIN estates e USING(estate_id) WHERE s.support_status='Unsupported' AND e.estate_name='Europe'"),
 c('e14','estate-chain','security incidents per estate','rows',`SELECT e.estate_name,count(*) FROM incidents i ${JOIN_EST} WHERE i.category='Security' GROUP BY 1`),
 c('e15','estate-chain','completed upgrades in the Asia Pacific estate','scalar',`SELECT count(*) FROM evergreening g ${JOIN_EST} WHERE g.evergreen_status='Completed' AND e.estate_name='Asia Pacific'`),
 // ---- incidents <-> vulnerabilities through servers ----
 c('x01','cross','how many servers have both an open critical vulnerability and a P1 incident','scalar',"SELECT count(*) FROM servers s WHERE EXISTS(SELECT 1 FROM vulnerabilities v WHERE v.server_id=s.server_id AND v.status='Open' AND v.severity='Critical') AND EXISTS(SELECT 1 FROM incidents i WHERE i.server_id=s.server_id AND i.priority='P1')"),
 c('x02','cross','servers with security incidents and internet exposed vulnerabilities - how many?','scalar',"SELECT count(*) FROM servers s WHERE EXISTS(SELECT 1 FROM incidents i WHERE i.server_id=s.server_id AND i.category='Security') AND EXISTS(SELECT 1 FROM vulnerabilities v WHERE v.server_id=s.server_id AND v.internet_exposed)"),
 c('x03','cross','how many servers have a failed backup and a major incident','scalar',"SELECT count(*) FROM servers s WHERE EXISTS(SELECT 1 FROM backups b WHERE b.server_id=s.server_id AND b.status='Failed') AND EXISTS(SELECT 1 FROM incidents i WHERE i.server_id=s.server_id AND i.major_incident)"),
 c('x04','cross','how many servers with blocked upgrades also have open critical vulnerabilities','scalar',"SELECT count(*) FROM servers s JOIN evergreening g USING(server_id) WHERE g.evergreen_status='Blocked' AND EXISTS(SELECT 1 FROM vulnerabilities v WHERE v.server_id=s.server_id AND v.status='Open' AND v.severity='Critical')"),
 c('x05','cross','servers with open vulnerabilities but no incidents','scalar',"SELECT count(*) FROM servers s WHERE EXISTS(SELECT 1 FROM vulnerabilities v WHERE v.server_id=s.server_id AND v.status='Open') AND NOT EXISTS(SELECT 1 FROM incidents i WHERE i.server_id=s.server_id)"),
 c('x06','cross','how many servers have never had a vulnerability','scalar','SELECT count(*) FROM servers s WHERE NOT EXISTS(SELECT 1 FROM vulnerabilities v WHERE v.server_id=s.server_id)'),
 c('x07','cross','how many servers have no backups at all','scalar','SELECT count(*) FROM servers s WHERE NOT EXISTS(SELECT 1 FROM backups b WHERE b.server_id=s.server_id)'),
 c('x08','cross','servers without any failed backup that have a P1 incident','scalar',"SELECT count(*) FROM servers s WHERE NOT EXISTS(SELECT 1 FROM backups b WHERE b.server_id=s.server_id AND b.status='Failed') AND EXISTS(SELECT 1 FROM incidents i WHERE i.server_id=s.server_id AND i.priority='P1')"),
 c('x09','cross','how many production servers have at least one open vulnerability','scalar',"SELECT count(DISTINCT s.server_id) FROM servers s JOIN vulnerabilities v USING(server_id) WHERE s.environment='Production' AND v.status='Open'"),
 c('x10','cross','how many applications have at least one major incident','scalar','SELECT count(DISTINCT a.application_id) FROM incidents i JOIN servers s USING(server_id) JOIN applications a USING(application_id) WHERE i.major_incident'),
 // ---- aggregates across joins ----
 c('g01','agg','average memory of servers running tier 1 applications','scalar',"SELECT avg(s.memory_gb) FROM servers s JOIN applications a USING(application_id) WHERE a.criticality='Tier 1'"),
 c('g02','agg','total backup size in GB for production servers','scalar',"SELECT sum(b.size_gb) FROM backups b JOIN servers s USING(server_id) WHERE s.environment='Production'"),
 c('g03','agg','max downtime of incidents on windows servers','scalar',"SELECT max(i.downtime_minutes) FROM incidents i JOIN servers s USING(server_id) WHERE s.os='Windows Server'"),
 c('g04','agg','average cvss score by package','rows','SELECT package_name,avg(cvss_score) FROM vulnerabilities GROUP BY 1'),
 c('g05','agg','average backup duration per destination','rows','SELECT destination,avg(duration_minutes) FROM backups GROUP BY 1'),
 c('g06','agg','minimum cpu cores in the Frankfurt datacenter','scalar',"SELECT min(cpu_cores) FROM servers WHERE datacenter='Frankfurt'"),
 c('g07','agg','total estimated upgrade cost per risk level','rows','SELECT risk_level,sum(estimated_cost) FROM evergreening GROUP BY 1'),
 c('g08','agg','average downtime per incident category','rows','SELECT category,avg(downtime_minutes) FROM incidents GROUP BY 1'),
 c('g09','agg','sum of disk space on aws servers','scalar',"SELECT sum(disk_gb) FROM servers WHERE platform='aws'"),
 c('g10','agg','average estimated cost of upgrades on unsupported servers','scalar',"SELECT avg(g.estimated_cost) FROM evergreening g JOIN servers s USING(server_id) WHERE s.support_status='Unsupported'"),
 c('g11','agg','how many distinct packages have open findings','scalar',"SELECT count(DISTINCT package_name) FROM vulnerabilities WHERE status='Open'"),
 c('g12','agg','how many different CVEs are open and critical','scalar',"SELECT count(DISTINCT cve) FROM vulnerabilities WHERE status='Open' AND severity='Critical'"),
 // ---- rankings ----
 c('r01','rank','top 5 servers by number of vulnerabilities','contains',undefined,[]),
 c('r02','rank','which application has the most servers','contains',undefined,[]),
 c('r03','rank','top 3 datacenters by incident count','contains',undefined,['Virginia']),
 c('r04','rank','which os has the most open critical vulnerabilities','contains',undefined,[]),
 c('r05','rank','bottom 2 countries by server count','contains',undefined,['JP']),
 c('r06','rank','which business unit has the most failed backups','contains',undefined,[]),
 c('r07','rank','which platform has the highest number of incidents','contains',undefined,[]),
 c('r08','rank','top 3 assigned teams by P1 incidents','contains',undefined,[]),
 c('r09','rank','which migration wave has the most blocked upgrades','contains',undefined,[]),
 c('r10','rank','which datacenter has the least production servers','contains',undefined,[]),
 c('r11','rank','top 2 estates by number of applications','contains',undefined,[]),
 c('r12','rank','which root cause has the longest average downtime','contains',undefined,[]),
 // ---- dates ----
 c('d01','dates','incidents created last month','scalar',`SELECT count(*) FROM incidents WHERE created_date>=date_trunc('month',${AS_OF})-INTERVAL 1 MONTH AND created_date<date_trunc('month',${AS_OF})`),
 c('d02','dates','how many vulnerabilities were discovered this month','scalar',`SELECT count(*) FROM vulnerabilities WHERE discovered_date>=date_trunc('month',${AS_OF}) AND discovered_date<date_trunc('month',${AS_OF})+INTERVAL 1 MONTH`),
 c('d03','dates','how many incidents in the past 14 days','scalar',[`SELECT count(*) FROM incidents WHERE created_date>=${AS_OF}-INTERVAL 14 DAY`,`SELECT count(*) FROM incidents WHERE created_date>${AS_OF}-INTERVAL 14 DAY`]),
 c('d04','dates','how many open vulnerabilities are overdue','scalar',[`SELECT count(*) FROM vulnerabilities WHERE status='Open' AND due_date<${AS_OF}`,`SELECT count(*) FROM vulnerabilities WHERE status='Open' AND due_date<=${AS_OF}`]),
 c('d05','dates','servers not patched in the last 90 days','scalar',[`SELECT count(*) FROM servers WHERE last_patch_date<${AS_OF}-INTERVAL 90 DAY`,`SELECT count(*) FROM servers WHERE last_patch_date<=${AS_OF}-INTERVAL 90 DAY`]),
 c('d06','dates','backups in the last 3 days','scalar',[`SELECT count(*) FROM backups WHERE started_at>=${AS_OF}-INTERVAL 3 DAY`,`SELECT count(*) FROM backups WHERE started_at>${AS_OF}-INTERVAL 3 DAY`]),
 c('d07','dates','incidents per month for the last 3 months','contains',undefined,[]),
 c('d08','dates','how many upgrades are due in the next 30 days','scalar',[`SELECT count(*) FROM evergreening WHERE target_date>=${AS_OF} AND target_date<${AS_OF}+INTERVAL 30 DAY`,`SELECT count(*) FROM evergreening WHERE target_date>=${AS_OF} AND target_date<=${AS_OF}+INTERVAL 30 DAY`,`SELECT count(*) FROM evergreening WHERE target_date>${AS_OF} AND target_date<=${AS_OF}+INTERVAL 30 DAY`]),
 c('d09','dates','when was the oldest open incident created','contains',undefined,[]),
 c('d10','dates','compare incidents this month and last month','contains',undefined,[]),
 c('d11','dates','critical vulnerabilities found in the last 7 days','scalar',[`SELECT count(*) FROM vulnerabilities WHERE severity='Critical' AND discovered_date>=${AS_OF}-INTERVAL 7 DAY`,`SELECT count(*) FROM vulnerabilities WHERE severity='Critical' AND discovered_date>${AS_OF}-INTERVAL 7 DAY`]),
 c('d12','dates','servers created this year','scalar',`SELECT count(*) FROM servers WHERE created_date>=date_trunc('year',${AS_OF})`),
 // ---- latest per entity ----
 c('l01','latest','how many servers had their latest backup succeed','scalar',"WITH r AS (SELECT *,row_number() OVER(PARTITION BY server_id ORDER BY started_at DESC,backup_id DESC) rn FROM backups) SELECT count(*) FROM r WHERE rn=1 AND status='Success'"),
 c('l02','latest','how many servers have their most recent incident still open','scalar',"WITH r AS (SELECT *,row_number() OVER(PARTITION BY server_id ORDER BY created_date DESC,incident_id DESC) rn FROM incidents) SELECT count(*) FROM r WHERE rn=1 AND status='Open'"),
 c('l03','latest','how many servers had a P1 as their latest incident','scalar',"WITH r AS (SELECT *,row_number() OVER(PARTITION BY server_id ORDER BY created_date DESC,incident_id DESC) rn FROM incidents) SELECT count(*) FROM r WHERE rn=1 AND priority='P1'"),
 c('l04','latest','how many servers whose last backup was a snapshot','scalar',"WITH r AS (SELECT *,row_number() OVER(PARTITION BY server_id ORDER BY started_at DESC,backup_id DESC) rn FROM backups) SELECT count(*) FROM r WHERE rn=1 AND backup_type='Snapshot'"),
 c('l05','latest','what is the most recent backup date','contains',undefined,['2026-10-07']),
 c('l06','latest','when did SRV-00003 last have an incident','contains',undefined,[]),
 // ---- shares ----
 c('p01','share','what percentage of incidents breached SLA','scalar','SELECT 100.0*count(*) FILTER (WHERE sla_breached)/count(*) FROM incidents'),
 c('p02','share','what percent of vulnerabilities are open','scalar',"SELECT 100.0*count(*) FILTER (WHERE status='Open')/count(*) FROM vulnerabilities"),
 c('p03','share','share of servers that are virtualized','scalar','SELECT 100.0*count(*) FILTER (WHERE virtualized)/count(*) FROM servers'),
 c('p04','share','percentage of backups that failed','scalar',"SELECT 100.0*count(*) FILTER (WHERE status='Failed')/count(*) FROM backups"),
 c('p05','share','what fraction of applications are regulated','scalar','SELECT avg(CASE WHEN regulated THEN 1.0 ELSE 0 END) FROM applications'),
 c('p06','share','percentage of upgrades that are completed','scalar',"SELECT 100.0*count(*) FILTER (WHERE evergreen_status='Completed')/count(*) FROM evergreening"),
 c('p07','share','what share of incidents had customer impact','scalar','SELECT 100.0*count(*) FILTER (WHERE customer_impact)/count(*) FROM incidents'),
 c('p08','share','percent of servers running ubuntu','scalar',"SELECT 100.0*count(*) FILTER (WHERE os='Ubuntu')/count(*) FROM servers"),
 // ---- lookups ----
 c('k01','lookup','what datacenter is host-03333 in','contains',undefined,[]),
 c('k02','lookup','how many incidents does host-00010 have','scalar',"SELECT count(*) FROM incidents i JOIN servers s USING(server_id) WHERE s.hostname='host-00010'"),
 c('k03','lookup','what os does SRV-02000 run','contains',undefined,[]),
 c('k04','lookup','which estate is Payments 1 in','contains',undefined,['Americas']),
 c('k05','lookup','how many servers does Identity 8 have','scalar',"SELECT count(*) FROM servers s JOIN applications a USING(application_id) WHERE a.application_name='Identity 8'"),
 c('k06','lookup','severity of VUL-100','contains',undefined,[]),
 c('k07','lookup','what is the priority of INC-7','contains',undefined,[]),
 c('k08','lookup','who is the owner email of APP-005','contains',undefined,['owner5@example.test']),
 c('k09','lookup','how many open vulnerabilities on host-00500','scalar',"SELECT count(*) FROM vulnerabilities v JOIN servers s USING(server_id) WHERE s.hostname='host-00500' AND v.status='Open'"),
 c('k10','lookup','what is the upgrade status of SRV-00001','contains',undefined,[]),
 // ---- distinct, booleans, nulls ----
 c('n01','null','how many incidents are unresolved','scalar',["SELECT count(*) FROM incidents WHERE resolved_date IS NULL","SELECT count(*) FROM incidents WHERE status IN ('Open','Investigating')"]),
 c('n02','null','how many vulnerabilities have a resolved date','scalar','SELECT count(*) FROM vulnerabilities WHERE resolved_date IS NOT NULL'),
 c('n03','null','how many backups have an error code','scalar','SELECT count(*) FROM backups WHERE error_code IS NOT NULL'),
 c('n04','null','how many upgrades have a blocker reason','scalar','SELECT count(*) FROM evergreening WHERE blocker_reason IS NOT NULL'),
 c('n05','null','how many distinct servers had incidents','scalar','SELECT count(DISTINCT server_id) FROM incidents'),
 c('n06','null','how many different assigned teams handle incidents','scalar','SELECT count(DISTINCT assigned_team) FROM incidents'),
 c('n07','null','how many internet exposed critical vulns','scalar',"SELECT count(*) FROM vulnerabilities WHERE internet_exposed AND severity='Critical'"),
 c('n08','null','backups that are not encrypted','scalar','SELECT count(*) FROM backups WHERE NOT encrypted'),
 c('n09','null','how many incidents did not breach SLA','scalar','SELECT count(*) FROM incidents WHERE NOT sla_breached'),
 c('n10','null','how many non-production servers','scalar',"SELECT count(*) FROM servers WHERE environment<>'Production'"),
 // ---- follow-ups ----
 c('f01','followup',['how many servers in London','what about Mumbai?'],'scalar',"SELECT count(*) FROM servers WHERE datacenter='Mumbai'"),
 c('f02','followup',['open vulnerabilities by severity','only for production servers'],'rows',"SELECT v.severity,count(*) FROM vulnerabilities v JOIN servers s USING(server_id) WHERE v.status='Open' AND s.environment='Production' GROUP BY 1"),
 c('f03','followup',['How many P1 incidents are there?','and P2?'],'scalar',"SELECT count(*) FROM incidents WHERE priority='P2'"),
 c('f04','followup',['count windows servers','of those how many are stopped'],'scalar',"SELECT count(*) FROM servers WHERE os='Windows Server' AND server_state='Stopped'"),
 c('f05','followup',['failed backups by type','same for partial'],'rows',"SELECT backup_type,count(*) FROM backups WHERE status='Partial' GROUP BY 1"),
 c('f06','followup',['How many servers does the Europe estate have?','and Americas?'],'scalar',"SELECT count(*) FROM servers s JOIN applications a USING(application_id) JOIN estates e USING(estate_id) WHERE e.estate_name='Americas'"),
 c('f07','followup',['incidents by category','break that down by priority instead'],'rows','SELECT priority,count(*) FROM incidents GROUP BY 1'),
 c('f08','followup',['how many blocked upgrades','what about in progress'],'scalar',"SELECT count(*) FROM evergreening WHERE evergreen_status='In progress'"),
 c('f09','followup',['average cvss of open vulnerabilities','and for remediated ones?'],'scalar',"SELECT avg(cvss_score) FROM vulnerabilities WHERE status='Remediated'"),
 c('f10','followup',['how many servers in Japan','how many of them are in production','and staging?'],'scalar',"SELECT count(*) FROM servers WHERE country='JP' AND environment='Staging'"),
 c('f11','followup',['top 3 applications by incident count','what about vulnerabilities?'],'contains',undefined,[]),
 c('f12','followup',['count critical vulns','how many of those are open'],'scalar',"SELECT count(*) FROM vulnerabilities WHERE severity='Critical' AND status='Open'"),
 // ---- multi-question ----
 c('m01','multi','how many servers are there and how many incidents?','contains',undefined,[4000,10000]),
 c('m02','multi','how many open incidents and how many open vulnerabilities?','contains',undefined,[]),
 c('m03','multi','count estates; count applications','contains',undefined,[4,80]),
 c('m04','multi','how many failed backups? how many blocked upgrades?','contains',undefined,[]),
 c('m05','multi','what is the average cvss and what is the max cvss?','contains',undefined,[9.9]),
 c('m06','multi','how many P1 incidents, and how many critical vulnerabilities?','contains',undefined,[]),
 // ---- edge cases ----
 c('z01','edge','how many servers are in Brazil','scalar','SELECT 0'),
 c('z02','edge','count incidents with priority P9','scalar','SELECT 0'),
 c('z03','edge','what is the revenue of each application','unsupported'),
 c('z04','edge','list employees in the security team','unsupported'),
 c('z05','edge','hi','contains',undefined,['servers']),
 c('z06','edge','thanks!','contains',undefined,[]),
 c('z07','edge','what tables do you have','contains',undefined,['incidents','vulnerabilities']),
 c('z08','edge',"servers where hostname = 'x' OR 1=1; DROP TABLE servers; --",'write'),
 c('z09','edge','insert a new server called test','write'),
 c('z10','edge','export all incidents to csv','write'),
 c('z11','edge','what about it','ambiguous'),
 c('z12','edge','asdfghjkl','ambiguous'),
 c('z13','edge','I need to know, for planning purposes and for the quarterly review that my director asked for, how many servers we currently have in the production environment located in the United States','scalar',"SELECT count(*) FROM servers WHERE environment='Production' AND country='US'"),
 c('z14','edge','HOW MANY VULNERABILITIES ARE CRITICAL AND OPEN???','scalar',"SELECT count(*) FROM vulnerabilities WHERE severity='Critical' AND status='Open'"),
 c('z15','edge','servers with more than 100 cpu cores','scalar','SELECT 0'),
 c('z16','edge','how many incidents have negative downtime','scalar','SELECT 0'),
 c('z17','edge','which columns are in backups','contains',undefined,['restore_test_status']),
 c('z18','edge','count everything in the vulnerabilities table','scalar','SELECT count(*) FROM vulnerabilities'),
 c('z19','edge','how many servers in GB with 64 GB memory','scalar',"SELECT count(*) FROM servers WHERE country='GB' AND memory_gb=64"),
 c('z20','edge','incidents in IN','scalar',"SELECT count(*) FROM incidents i JOIN servers s USING(server_id) WHERE s.country='IN'"),
];
// Contains-checks with empty expectations are filled from oracle SQL at run time.
export const battery150Oracles:Record<string,string>={
 r02:'SELECT a.application_name FROM servers s JOIN applications a USING(application_id) GROUP BY 1 ORDER BY count(*) DESC, 1 LIMIT 1',
 r04:"SELECT s.os FROM vulnerabilities v JOIN servers s USING(server_id) WHERE v.status='Open' AND v.severity='Critical' GROUP BY 1 ORDER BY count(*) DESC LIMIT 1",
 r06:"SELECT a.business_unit FROM backups b JOIN servers s USING(server_id) JOIN applications a USING(application_id) WHERE b.status='Failed' GROUP BY 1 ORDER BY count(*) DESC LIMIT 1",
 r07:'SELECT s.platform FROM incidents i JOIN servers s USING(server_id) GROUP BY 1 ORDER BY count(*) DESC LIMIT 1',
 r08:"SELECT assigned_team FROM incidents WHERE priority='P1' GROUP BY 1 ORDER BY count(*) DESC, 1 LIMIT 1",
 r09:"SELECT migration_wave FROM evergreening WHERE evergreen_status='Blocked' GROUP BY 1 ORDER BY count(*) DESC LIMIT 1",
 r10:"SELECT datacenter FROM servers WHERE environment='Production' GROUP BY 1 ORDER BY count(*) ASC LIMIT 1",
 r11:'SELECT e.estate_name FROM applications a JOIN estates e USING(estate_id) GROUP BY 1 ORDER BY count(*) DESC, 1 LIMIT 1',
 r12:'SELECT root_cause FROM incidents GROUP BY 1 ORDER BY avg(downtime_minutes) DESC LIMIT 1',
 d07:`SELECT count(*) FROM incidents WHERE created_date>=date_trunc('month',${AS_OF}) AND created_date<date_trunc('month',${AS_OF})+INTERVAL 1 MONTH`,
 d09:"SELECT strftime(min(created_date),'%Y-%m-%d') FROM incidents WHERE status='Open'",
 d10:`SELECT count(*) FROM incidents WHERE created_date>=date_trunc('month',${AS_OF})-INTERVAL 1 MONTH AND created_date<date_trunc('month',${AS_OF})`,
 l06:"SELECT strftime(max(created_date),'%Y-%m-%d') FROM incidents WHERE server_id='SRV-00003'",
 k01:"SELECT datacenter FROM servers WHERE hostname='host-03333'",
 k03:"SELECT os FROM servers WHERE server_id='SRV-02000'",
 k06:"SELECT severity FROM vulnerabilities WHERE vulnerability_id='VUL-100'",
 k07:"SELECT priority FROM incidents WHERE incident_id='INC-7'",
 k10:"SELECT evergreen_status FROM evergreening WHERE server_id='SRV-00001'",
 f11:'SELECT a.application_name FROM vulnerabilities v JOIN servers s USING(server_id) JOIN applications a USING(application_id) GROUP BY 1 ORDER BY count(*) DESC, 1 LIMIT 1',
 m02:"SELECT (SELECT count(*) FROM incidents WHERE status='Open') UNION ALL SELECT (SELECT count(*) FROM vulnerabilities WHERE status='Open')",
 m04:"SELECT (SELECT count(*) FROM backups WHERE status='Failed') UNION ALL SELECT (SELECT count(*) FROM evergreening WHERE evergreen_status='Blocked')",
 m06:"SELECT (SELECT count(*) FROM incidents WHERE priority='P1') UNION ALL SELECT (SELECT count(*) FROM vulnerabilities WHERE severity='Critical')",
 r01:"SELECT count(*) n FROM vulnerabilities GROUP BY server_id ORDER BY n DESC LIMIT 1",
};
