// 100-question evaluation set across every table, written after the harness changes.
// Never imported by backend code. Oracles are independent SQL; checks are column-name independent.
import type {BatteryCase} from './battery-cases.js';
const c=(id:string,category:string,turns:string|string[],check:BatteryCase['check'],oracle?:string|string[],values?:(string|number)[]):BatteryCase=>({id,split:'fresh',category,turns:Array.isArray(turns)?turns:[turns],check,oracle,values});
const AS_OF="(SELECT as_of FROM dataset_info)";
export const battery100:BatteryCase[]=[
 // ---- servers ----
 c('s01','servers','How many servers are there in total?','scalar','SELECT count(*) FROM servers'),
 c('s02','servers','how many staging boxes do we run','scalar',"SELECT count(*) FROM servers WHERE environment='Staging'"),
 c('s03','servers','Count the servers in Mumbai','scalar',"SELECT count(*) FROM servers WHERE datacenter='Mumbai'"),
 c('s04','servers','how many servers are currently stopped?','scalar',"SELECT count(*) FROM servers WHERE server_state='Stopped'"),
 c('s05','servers','number of virtualized servers','scalar','SELECT count(*) FROM servers WHERE virtualized'),
 c('s06','servers','servers by platform','rows','SELECT platform,count(*) FROM servers GROUP BY 1'),
 c('s07','servers','How many servers does each region have?','rows','SELECT region,count(*) FROM servers GROUP BY 1'),
 c('s08','servers','average CPU cores on SUSE servers','scalar',"SELECT avg(cpu_cores) FROM servers WHERE os='SUSE Linux'"),
 c('s09','servers','What is the largest disk size of any server?','scalar','SELECT max(disk_gb) FROM servers'),
 c('s10','servers','total memory of production servers in the US','scalar',"SELECT sum(memory_gb) FROM servers WHERE environment='Production' AND country='US'"),
 c('s11','servers','how many servers are in Retiring lifecycle state','scalar',"SELECT count(*) FROM servers WHERE lifecycle_state='Retiring'"),
 c('s12','servers','Which country has the fewest servers?','contains',undefined,['JP']),
 c('s13','servers','how many servers have extended support','scalar',"SELECT count(*) FROM servers WHERE support_status='Extended'"),
 c('s14','servers','windows servers on aws - how many?','scalar',"SELECT count(*) FROM servers WHERE os='Windows Server' AND platform='aws'"),
 // ---- vulnerabilities ----
 c('v01','vulns','How many vulnerability findings are there?','scalar','SELECT count(*) FROM vulnerabilities'),
 c('v02','vulns','how many high severity vulns are still open','scalar',"SELECT count(*) FROM vulnerabilities WHERE severity='High' AND status='Open'"),
 c('v03','vulns','vulnerabilities by status','rows','SELECT status,count(*) FROM vulnerabilities GROUP BY 1'),
 c('v04','vulns','Which package has the most open vulnerabilities?','contains',undefined,['kernel']),
 c('v05','vulns','average CVSS score of critical findings','scalar',"SELECT avg(cvss_score) FROM vulnerabilities WHERE severity='Critical'"),
 c('v06','vulns','how many findings have an approved exception','scalar','SELECT count(*) FROM vulnerabilities WHERE exception_approved'),
 c('v07','vulns','count accepted vulnerabilities','scalar',"SELECT count(*) FROM vulnerabilities WHERE status='Accepted'"),
 c('v08','vulns','how many open vulns can be fixed with a patch','scalar',"SELECT count(*) FROM vulnerabilities WHERE status='Open' AND remediation='Patch'"),
 c('v09','vulns','What is the highest cvss score among open findings?','scalar',"SELECT max(cvss_score) FROM vulnerabilities WHERE status='Open'"),
 c('v10','vulns','open vulnerabilities per severity','rows',"SELECT severity,count(*) FROM vulnerabilities WHERE status='Open' GROUP BY 1"),
 c('v11','vulns','how many nginx findings are there','scalar',"SELECT count(*) FROM vulnerabilities WHERE package_name='nginx'"),
 c('v12','vulns','vulnerabilities found by scanner-2','scalar',"SELECT count(*) FROM vulnerabilities WHERE source='scanner-2'"),
 // ---- incidents ----
 c('i01','incidents','How many incidents do we have?','scalar','SELECT count(*) FROM incidents'),
 c('i02','incidents','how many incidents are under investigation','scalar',"SELECT count(*) FROM incidents WHERE status='Investigating'"),
 c('i03','incidents','incidents by category','rows','SELECT category,count(*) FROM incidents GROUP BY 1'),
 c('i04','incidents','how many major incidents','scalar','SELECT count(*) FROM incidents WHERE major_incident'),
 c('i05','incidents','How many incidents breached their SLA?','scalar','SELECT count(*) FROM incidents WHERE sla_breached'),
 c('i06','incidents','average downtime of P1 incidents','scalar',"SELECT avg(downtime_minutes) FROM incidents WHERE priority='P1'"),
 c('i07','incidents','total downtime minutes for availability incidents','scalar',"SELECT sum(downtime_minutes) FROM incidents WHERE category='Availability'"),
 c('i08','incidents','Which root cause is most common?','contains',undefined,['Capacity']),
 c('i09','incidents','incidents per root cause','rows','SELECT root_cause,count(*) FROM incidents GROUP BY 1'),
 c('i10','incidents','how many critical severity incidents are closed','scalar',"SELECT count(*) FROM incidents WHERE severity='Critical' AND status='Closed'"),
 c('i11','incidents','how many incidents had customer impact','scalar','SELECT count(*) FROM incidents WHERE customer_impact'),
 c('i12','incidents','which team is assigned the most incidents?','contains',undefined,['ops-4']),
 // ---- backups ----
 c('b01','backups','How many backup runs are there?','scalar','SELECT count(*) FROM backups'),
 c('b02','backups','how many backups partially succeeded','scalar',"SELECT count(*) FROM backups WHERE status='Partial'"),
 c('b03','backups','backups by type','rows','SELECT backup_type,count(*) FROM backups GROUP BY 1'),
 c('b04','backups','how many backups are immutable','scalar','SELECT count(*) FROM backups WHERE immutable'),
 c('b05','backups','average backup size in GB','scalar','SELECT avg(size_gb) FROM backups'),
 c('b06','backups','how many backups went to object storage','scalar',"SELECT count(*) FROM backups WHERE destination='Object Storage'"),
 c('b07','backups','count of failed snapshot backups','scalar',"SELECT count(*) FROM backups WHERE status='Failed' AND backup_type='Snapshot'"),
 c('b08','backups','restore test results breakdown','rows','SELECT restore_test_status,count(*) FROM backups GROUP BY 1'),
 c('b09','backups','longest backup duration in minutes','scalar','SELECT max(duration_minutes) FROM backups'),
 c('b10','backups','how many backups failed with a timeout error','scalar',"SELECT count(*) FROM backups WHERE error_code='BKP_TIMEOUT'"),
 // ---- evergreening ----
 c('e01','evergreen','how many OS upgrades are completed','scalar',"SELECT count(*) FROM evergreening WHERE evergreen_status='Completed'"),
 c('e02','evergreen','upgrade status breakdown','rows','SELECT evergreen_status,count(*) FROM evergreening GROUP BY 1'),
 c('e03','evergreen','how many high risk upgrades are in progress','scalar',"SELECT count(*) FROM evergreening WHERE risk_level='High' AND evergreen_status='In progress'"),
 c('e04','evergreen','average estimated upgrade cost','scalar','SELECT avg(estimated_cost) FROM evergreening'),
 c('e05','evergreen','how many upgrades are in wave-3','scalar',"SELECT count(*) FROM evergreening WHERE migration_wave='wave-3'"),
 c('e06','evergreen','how many upgrades have not started','scalar',"SELECT count(*) FROM evergreening WHERE evergreen_status='Not started'"),
 c('e07','evergreen','total estimated cost of blocked upgrades','scalar',"SELECT sum(estimated_cost) FROM evergreening WHERE evergreen_status='Blocked'"),
 c('e08','evergreen','upgrades per risk level','rows','SELECT risk_level,count(*) FROM evergreening GROUP BY 1'),
 // ---- applications & estates ----
 c('a01','apps','How many applications are tier 2?','scalar',"SELECT count(*) FROM applications WHERE criticality='Tier 2'"),
 c('a02','apps','how many regulated applications','scalar','SELECT count(*) FROM applications WHERE regulated'),
 c('a03','apps','applications per business unit','rows','SELECT business_unit,count(*) FROM applications GROUP BY 1'),
 c('a04','apps','how many gold service tier apps are customer facing','scalar',"SELECT count(*) FROM applications WHERE service_tier='Gold' AND customer_type='Customer'"),
 c('a05','apps','how many applications does each estate own','rows','SELECT e.estate_name,count(*) FROM applications a JOIN estates e USING(estate_id) GROUP BY 1'),
 c('a06','apps','Which team owns the Asia Pacific estate?','contains',undefined,['Technology']),
 c('a07','apps','list all estates','contains',undefined,['Americas','Europe','Asia Pacific','Shared Services']),
 c('a08','apps','what is the headquarters country of the Shared Services estate','contains',undefined,['DE']),
 // ---- two-table joins ----
 c('j01','join2','how many vulnerabilities are on production servers','scalar',"SELECT count(*) FROM vulnerabilities v JOIN servers s USING(server_id) WHERE s.environment='Production'"),
 c('j02','join2','how many incidents happened on windows servers','scalar',"SELECT count(*) FROM incidents i JOIN servers s USING(server_id) WHERE s.os='Windows Server'"),
 c('j03','join2','failed backups on servers in London','scalar',"SELECT count(*) FROM backups b JOIN servers s USING(server_id) WHERE b.status='Failed' AND s.datacenter='London'"),
 c('j04','join2','how many servers in Germany have open critical vulnerabilities','scalar',"SELECT count(DISTINCT s.server_id) FROM servers s JOIN vulnerabilities v USING(server_id) WHERE s.country='DE' AND v.status='Open' AND v.severity='Critical'"),
 c('j05','join2','how many servers are on tier 1 applications','scalar',"SELECT count(*) FROM servers s JOIN applications a USING(application_id) WHERE a.criticality='Tier 1'"),
 c('j06','join2','open vulnerabilities by server environment','rows',"SELECT s.environment,count(*) FROM vulnerabilities v JOIN servers s USING(server_id) WHERE v.status='Open' GROUP BY 1"),
 c('j07','join2','incidents by server operating system','rows','SELECT s.os,count(*) FROM incidents i JOIN servers s USING(server_id) GROUP BY 1'),
 c('j08','join2','how many blocked upgrades are on production servers','scalar',"SELECT count(*) FROM evergreening e JOIN servers s USING(server_id) WHERE e.evergreen_status='Blocked' AND s.environment='Production'"),
 c('j09','join2','How many servers have at least one P1 incident?','scalar',"SELECT count(DISTINCT server_id) FROM incidents WHERE priority='P1'"),
 c('j10','join2','which datacenter has the most security incidents','contains',undefined,['Virginia']),
 c('j11','join2','how many servers run regulated applications','scalar','SELECT count(*) FROM servers s JOIN applications a USING(application_id) WHERE a.regulated'),
 c('j12','join2','How many servers have never had an incident?','scalar','SELECT count(*) FROM servers s WHERE NOT EXISTS(SELECT 1 FROM incidents i WHERE i.server_id=s.server_id)'),
 // ---- three/four-table joins ----
 c('k01','join3','open vulnerabilities per estate','rows',"SELECT e.estate_name,count(*) FROM vulnerabilities v JOIN servers s USING(server_id) JOIN applications a USING(application_id) JOIN estates e USING(estate_id) WHERE v.status='Open' GROUP BY 1"),
 c('k02','join3','which estate has the most incidents','contains',undefined,['Asia Pacific',2571]),
 c('k03','join3','top 3 applications by number of incidents','contains',undefined,['Logistics 63']),
 c('k04','join3','failed backups per business unit of the application','rows',"SELECT a.business_unit,count(*) FROM backups b JOIN servers s USING(server_id) JOIN applications a USING(application_id) WHERE b.status='Failed' GROUP BY 1"),
 c('k05','join3','how many critical vulnerabilities are on tier 1 applications','scalar',"SELECT count(*) FROM vulnerabilities v JOIN servers s USING(server_id) JOIN applications a USING(application_id) WHERE v.severity='Critical' AND a.criticality='Tier 1'"),
 c('k06','join3','major incidents in the Europe estate','scalar',"SELECT count(*) FROM incidents i JOIN servers s USING(server_id) JOIN applications a USING(application_id) JOIN estates e USING(estate_id) WHERE i.major_incident AND e.estate_name='Europe'"),
 c('k07','join3','servers per estate','rows','SELECT e.estate_name,count(*) FROM servers s JOIN applications a USING(application_id) JOIN estates e USING(estate_id) GROUP BY 1'),
 c('k08','join3','which application has the most blocked upgrades','contains',undefined,[22]),
 c('k09','join3','how many open vulnerabilities do regulated applications have','scalar',"SELECT count(*) FROM vulnerabilities v JOIN servers s USING(server_id) JOIN applications a USING(application_id) WHERE v.status='Open' AND a.regulated"),
 c('k10','join3','incident count by application criticality','rows','SELECT a.criticality,count(*) FROM incidents i JOIN servers s USING(server_id) JOIN applications a USING(application_id) GROUP BY 1'),
 // ---- dates ----
 c('d01','dates','How many incidents were created this month?','scalar',`SELECT count(*) FROM incidents WHERE created_date>=date_trunc('month',${AS_OF}) AND created_date<date_trunc('month',${AS_OF})+INTERVAL 1 MONTH`),
 c('d02','dates','how many vulnerabilities were discovered in the last 30 days','scalar',[`SELECT count(*) FROM vulnerabilities WHERE discovered_date>=${AS_OF}-INTERVAL 30 DAY`,`SELECT count(*) FROM vulnerabilities WHERE discovered_date>${AS_OF}-INTERVAL 30 DAY`]),
 c('d03','dates','how many open vulnerabilities are due in the next 7 days','scalar',[`SELECT count(*) FROM vulnerabilities WHERE status='Open' AND due_date>=${AS_OF} AND due_date<=${AS_OF}+INTERVAL 7 DAY`,`SELECT count(*) FROM vulnerabilities WHERE status='Open' AND due_date>=${AS_OF} AND due_date<${AS_OF}+INTERVAL 7 DAY`,`SELECT count(*) FROM vulnerabilities WHERE status='Open' AND due_date>${AS_OF} AND due_date<=${AS_OF}+INTERVAL 7 DAY`]),
 c('d04','dates','How many upgrades completed last month?','scalar',`SELECT count(*) FROM evergreening WHERE completed_date>=date_trunc('month',${AS_OF})-INTERVAL 1 MONTH AND completed_date<date_trunc('month',${AS_OF})`),
 c('d05','dates','backups started in the last 7 days','scalar',[`SELECT count(*) FROM backups WHERE started_at>=${AS_OF}-INTERVAL 7 DAY`,`SELECT count(*) FROM backups WHERE started_at>${AS_OF}-INTERVAL 7 DAY`]),
 c('d06','dates','when was the most recent incident created','contains',undefined,['2026-10-07']),
 // ---- lookups ----
 c('l01','lookup','what environment is host-00777 in?','contains',undefined,['Production']),
 c('l02','lookup','who owns application APP-012?','contains',undefined,['team-12']),
 c('l03','lookup','how many vulnerabilities does SRV-00100 have','scalar',"SELECT count(*) FROM vulnerabilities WHERE server_id='SRV-00100'"),
 c('l04','lookup','what is the status of incident INC-42','contains',undefined,['Investigating']),
 // ---- follow-ups ----
 c('f01','followup',['How many servers are in Japan?','and how many of those are production?'],'scalar',"SELECT count(*) FROM servers WHERE country='JP' AND environment='Production'"),
 c('f02','followup',['how many open critical vulnerabilities are there?','what about high?'],'scalar',"SELECT count(*) FROM vulnerabilities WHERE status='Open' AND severity='High'"),
 c('f03','followup',['incidents by priority','now only for security incidents'],'rows',"SELECT priority,count(*) FROM incidents WHERE category='Security' GROUP BY 1"),
 c('f04','followup',['How many failed backups are there?','same for partial'],'scalar',"SELECT count(*) FROM backups WHERE status='Partial'"),
 // ---- guardrails ----
 c('g01','guard','delete all failed backups','write'),
 c('g02','guard','what is the weather in London today?','unsupported'),
 c('g03','guard','show me everything wrong','ambiguous'),
 c('g04','guard','which columns does the incidents table have?','contains',undefined,['priority','downtime_minutes']),
];
