import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {Database} from '../backend/db.js';import {Catalog} from '../backend/catalog.js';import {Executor} from '../backend/executor.js';import {Agent,emptyState} from '../backend/agent.js';import {resolveContract,compileContract,verifyContract} from '../backend/contracts.js';import type {Model} from '../backend/llm.js';import type {Trace} from '../backend/types.js';
let db:Database,catalog:Catalog;before(async()=>{db=await Database.open();catalog=await new Catalog(db,null).build();});after(()=>db.close());
const execute=async(question:string)=>{const c=resolveContract(question,catalog)!;assert.ok(c);const t:Trace={question,intent:question,schema:null,plans:[],events:[],evidence:[],llm:[],retries:0,totalMs:0};await new Executor(catalog,async()=>{throw new Error('Compiled operations should not need SQL drafting');}).execute(compileContract(c,catalog),t,emptyState(),()=>{});return {c,result:verifyContract(c,t.evidence),trace:t};};
for(const [question,table,column] of [['Summarize different OS','servers','os'],['Count servers in each country','servers','country'],['Group vulnerability findings by severity','vulnerabilities','severity'],['Give backup counts by status','backups','status']])test('category operator matches independent oracle: '+question,async()=>{const {result}=await execute(question);assert.deepEqual(result.rows,(await db.query(`SELECT ${column},count(*) record_count FROM ${table} GROUP BY ${column} ORDER BY record_count DESC,${column}`)).rows);});
test('latest-related operation returns three unique US servers and their actual latest incident',async()=>{
 const {result,trace}=await execute('Show three US servers with their OS and latest incident.');assert.equal(result.rows.length,3);assert.equal(new Set(result.rows.map(r=>r.server_id)).size,3);assert.equal(trace.evidence.length,2);
 const oracle=(await db.query("SELECT s.server_id,s.os,s.country,(SELECT incident_id FROM incidents i WHERE i.server_id=s.server_id ORDER BY created_date DESC NULLS LAST,incident_id DESC LIMIT 1) latest_incident_id,(SELECT created_date FROM incidents i WHERE i.server_id=s.server_id ORDER BY created_date DESC NULLS LAST,incident_id DESC LIMIT 1) latest_created_date FROM servers s WHERE country='US' ORDER BY server_id LIMIT 3")).rows;
 assert.deepEqual(result.rows,oracle);
});
test('numeric measures and distinct-category counts do not get replaced by group counts',()=>{assert.equal(resolveContract('Average memory_gb by OS',catalog),null);assert.equal(resolveContract('How many different OS are there?',catalog),null);});
test('new categorical summary drops earlier selected IDs and keeps tracked steps',async()=>{
 const llm:Model=async(schema,purpose,_system,input)=>{if(purpose==='Operation planning')return schema.parse({steps:[{objective:'Execute verified operations'}]});assert.equal(purpose,'Intent');return schema.parse({access:'read',request:(input as {question:string}).question,concepts:[],filters:[],timeRange:'',aliases:[]});};
 const agent=new Agent(catalog,llm);const first=await agent.ask('Show three US servers with their OS and latest incident.');assert.equal(first.status,'answered');
 const summary=await agent.ask('summarize abut the data about diferent os',first.sessionId);assert.equal(summary.status,'answered');assert.equal(summary.evidence[0].rows.reduce((n,r)=>n+Number(r.record_count),0),4000);assert.ok(summary.trace.checklist?.every(s=>s.status==='verified'));assert.equal(summary.state.selectedIds.length,0);
});
