import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rename,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {DuckDBInstance} from '@duckdb/node-api';import {Database} from '../backend/db.js';import {Catalog} from '../backend/catalog.js';import {resolveContract,compileContract,verifyContract} from '../backend/contracts.js';import {Executor} from '../backend/executor.js';import {emptyState} from '../backend/agent.js';import type {Trace} from '../backend/types.js';
async function fixture(path:string,sql:string){const instance=await DuckDBInstance.create(path);const c=await instance.connect();try{await c.run(sql);}finally{c.closeSync();instance.closeSync();}}
test('snapshot replacement refreshes schema, values, profiles and joins automatically',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'jevy-refresh-'));const path=join(dir,'estate.duckdb');let db:Database|undefined;
 try{
  await fixture(path,"CREATE TABLE devices(device_id VARCHAR,os VARCHAR); INSERT INTO devices VALUES ('D1','Alpha'),('D2','Beta');");db=await Database.open(path);const catalog=await new Catalog(db,null).build();const original=catalog.version;
  await Promise.all([catalog.build(),catalog.build()]);assert.equal(catalog.tables.length,1);assert.equal(catalog.version,original);
  const replacement=join(dir,'next.duckdb');await fixture(replacement,"CREATE TABLE devices(device_id VARCHAR,os VARCHAR,ram INTEGER); INSERT INTO devices VALUES ('D1','Gamma',4),('D2','Delta',8),('D3','Gamma',16); CREATE TABLE alerts(alert_id VARCHAR,device_id VARCHAR,created_date TIMESTAMP); INSERT INTO alerts VALUES ('A1','D1','2026-01-01'),('A2','D1','2026-02-01');");await rename(replacement,path);
  await catalog.ensureFresh();assert.equal(db.revision,1);assert.equal(catalog.version,original+1);assert.equal(catalog.table('devices').rowCount,3);assert.deepEqual(catalog.table('devices').columns.find(c=>c.name==='os')!.values,['Delta','Gamma']);assert.equal(catalog.table('devices').columns.find(c=>c.name==='ram')!.profile?.max,16);assert.ok(catalog.table('alerts').relationships.includes('alerts.device_id = devices.device_id'));
  const contract=resolveContract('Show three devices with OS and latest alert',catalog)!;assert.ok(contract);const trace:Trace={question:contract.question,intent:contract.question,schema:null,plans:[],events:[],evidence:[],llm:[],retries:0,totalMs:0};await new Executor(catalog,async()=>{throw new Error('No model SQL needed');}).execute(compileContract(contract,catalog),trace,emptyState(),()=>{});const result=verifyContract(contract,trace.evidence);assert.equal(result.rows.length,3);assert.equal(result.rows[0].latest_alert_id,'A2');assert.equal(result.rows[1].latest_alert_id,null);
 }finally{db?.close();await rm(dir,{recursive:true,force:true});}
});
test('failed refresh preserves last complete catalog and exposes refresh error',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'jevy-refresh-error-'));const path=join(dir,'estate.duckdb');let db:Database|undefined;
 try{await fixture(path,"CREATE TABLE things(thing_id VARCHAR); INSERT INTO things VALUES ('T1');");db=await Database.open(path);const catalog=await new Catalog(db,null).build();const previous=catalog.tables;const query=db.query.bind(db);db.query=async()=>{throw new Error('scan failed');};await assert.rejects(catalog.build(),/scan failed/);assert.equal(catalog.tables,previous);assert.equal(catalog.refreshError,'scan failed');db.query=query;await catalog.build();assert.equal(catalog.refreshError,'');}finally{db?.close();await rm(dir,{recursive:true,force:true});}
});
