import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {Database} from '../backend/db.js';import {Catalog} from '../backend/catalog.js';import {Agent} from '../backend/agent.js';
const db=await Database.open(),agent=new Agent(await new Catalog(db,null).build());const results=[];let session:string|undefined;
const questions=['Show three US servers with their OS and latest incident.','give me three random servers and give a write up abou tthem like a song','summarize abut the data about diferent os','summarize abut the data about diferent os\nand wriete a write up .. about differnet OS we have','Summarize server inventory by environment.','Pick five random GB servers with hostname and most recent backup.'];
try{for(const question of questions){const a=await agent.ask(question,session);session=a.sessionId;let correct=a.status==='answered';
 if(question.includes('latest incident')){const rows=a.evidence[0]?.rows||[];correct&&=rows.length===3&&new Set(rows.map(r=>r.server_id)).size===3;for(const row of rows){const actual=(await db.query(`SELECT os,country,(SELECT incident_id FROM incidents i WHERE i.server_id=s.server_id ORDER BY created_date DESC NULLS LAST,incident_id DESC LIMIT 1) latest_incident_id FROM servers s WHERE server_id='${row.server_id}'`)).rows[0];correct&&=row.os===actual.os&&row.country==='US'&&row.latest_incident_id===actual.latest_incident_id;}}
 else if(question.includes('song'))correct&&=a.evidence.flatMap(e=>e.rows).length===3;
 else if(question.includes('backup.')){const rows=a.evidence[0]?.rows||[];correct&&=rows.length===5;for(const row of rows){const actual=(await db.query(`SELECT country,(SELECT backup_id FROM backups b WHERE b.server_id=s.server_id ORDER BY started_at DESC NULLS LAST,backup_id DESC LIMIT 1) latest_backup_id FROM servers s WHERE server_id='${row.server_id}'`)).rows[0];correct&&=row.country==='GB'&&row.latest_backup_id===actual.latest_backup_id;}}
 else correct&&=a.evidence[0]?.rows.reduce((n,r)=>n+Number(r.record_count),0)===4000;
 results.push({question,correct,status:a.status,ms:a.trace.totalMs,calls:a.trace.llm.length,answer:a});await writeFile('test-results/conversation-regression.json',JSON.stringify(results,null,2));console.log(JSON.stringify({question,correct,status:a.status,ms:Math.round(a.trace.totalMs),calls:a.trace.llm.length,rows:a.evidence.map(e=>e.rowCount)}));}
 assert.ok(results.every(r=>r.correct),'Conversation regression failed');}finally{db.close();}
