import {cases} from '../tests/cases.js';
import {readFile,writeFile} from 'node:fs/promises';
const report=JSON.parse(await readFile(process.env.EVAL_OUTPUT||'test-results/evaluation.json','utf8'));
const {summary:s,results}=report;
const pct=(v:number|null)=>v===null?'not measured':(v*100).toFixed(1)+'%';
const caseMap=new Map(cases.map(c=>[c.id,c]));
const data=results.filter((r:{id:string})=>!['write','unsupported','ambiguous'].includes(caseMap.get(r.id)?.kind||''));
const answered=data.filter((r:{status:string})=>r.status==='answered');
const precise=answered.filter((r:{correct:boolean})=>r.correct).length;
const passed=results.filter((r:{correct:boolean})=>r.correct).length;
const lines=[`# Jevy live-model evaluation`,``,`Measured ${s.date}. Local model: ${s.model}. Seed ${s.seed}, reference date ${s.asOf}.`,``,`Coverage: **${s.tested}/${s.totalCases} cases**, **${passed} passed**, **${s.tested-passed} failed**. ${s.tested===s.totalCases?'Complete run.':'Partial run; do not interpret as full-suite accuracy.'}`,``,`| Measure | Result |`,`|---|---|`,`| Final evidence accuracy | ${pct(s.finalEvidenceAccuracy)} |`,`| SQL step completion after bounded repair and review | ${pct(s.sqlExecutionSuccessRate)} |`,`| Mean repairs per final turn | ${s.averageRetries.toFixed(2)} |`,`| Mean model calls per final turn | ${s.averageLlmCalls.toFixed(2)} |`,`| Mean model latency per final turn | ${(s.averageLlmLatencyMs/1000).toFixed(1)} s |`,`| Mean total response latency per final turn | ${(s.averageResponseLatencyMs/1000).toFixed(1)} s |`,``,`Accuracy means ${s.accuracyDefinition}`,``,`SQL step completion includes execution and review acceptance. It does not establish correct filters, joins, entity scope or complete coverage of a compound request. The evidence renderer prevents invented facts, but semantically wrong SQL can still produce a wrong answer. This experiment must not be treated as proof of arbitrary-question reliability.`,``,`## Per-case results`,``,`| Case | Passed | Status | Latency | Model calls | Repairs |`,`|---|---|---|---|---|---|`,...results.map((r:{id:string;correct:boolean;status:string;latencyMs:number;llmCalls:number;retries:number})=>`| ${r.id} | ${r.correct?'yes':'no'} | ${r.status} | ${(r.latencyMs/1000).toFixed(1)} s | ${r.llmCalls} | ${r.retries} |`),``,`## Review failures`,``,`For full SQL, plans, observations, execution errors and returned rows, inspect [the measured JSON trace](${process.env.EVAL_OUTPUT||'test-results/evaluation.json'}). To repeat a capability test and wording variants, use EVAL_FILTER with the IDs above. Each evaluation rereads DuckDB; no factual answers are cached.`,``,`The evaluator uses a conservative exact comparison for deterministic query results. Random/compound cases additionally require requested entity attributes, independent counts and the most recent incident. Column alias differences in compound evidence may cause a failure even when some values are correct; inspect the trace before changing the agent.`,``,`Follow-up metrics describe the final follow-up turn. Unsupported, ambiguous and attempted-write cases use status-based checks; they are not numeric answer-accuracy cases.`,``,`79 core safety/orchestration/provider checks passed; logs are separate in test-results/core-current.log.`,``];
lines.push('## Answer coverage and precision','',`Data requests answered: ${answered.length}/${data.length} (${pct(data.length?answered.length/data.length:null)}). Correct among answered data requests: ${precise}/${answered.length} (${pct(answered.length?precise/answered.length:null)}). Unsupported, write and ambiguity status cases are excluded from these two measures. Every incomplete or incorrect data answer still counts as failure in overall accuracy above.`, '', 'Latency is a local-machine measurement. Concurrent local workloads were observed during development; this is not a controlled idle-machine speed comparison.','');
try{const baseline=JSON.parse(await readFile('test-results/qwen3-free-sql-full.json','utf8'));const common=results.filter((r:{id:string})=>baseline.results.some((b:{id:string})=>b.id===r.id));const oldPassed=common.filter((r:{id:string})=>baseline.results.find((b:{id:string})=>b.id===r.id).correct).length;const newPassed=common.filter((r:{correct:boolean})=>r.correct).length;lines.push('## Matched question comparison','',`On the ${common.length} shared question IDs, the free-SQL baseline passed ${oldPassed}/${common.length}; this regression passed ${newPassed}/${common.length}. Same local model, synthetic seed and reference date. This compares factual case outcomes, not a controlled latency benchmark. Selected coverage does not establish full-suite accuracy.`, '');}catch{}
try{const prior=JSON.parse(await readFile('test-results/compiler-baseline.json','utf8'));const matched=results.filter((r:{id:string})=>prior.results.some((p:{id:string})=>p.id===r.id));lines.push('## Previous compiler comparison','',`For the ${matched.length} shared IDs, the previous compiler passed ${matched.filter((r:{id:string})=>prior.results.find((p:{id:string})=>p.id===r.id).correct).length}/${matched.length}; the active harness passed ${matched.filter((r:{correct:boolean})=>r.correct).length}/${matched.length}. Coverage and latency should be judged separately.`, '');}catch{}
await writeFile('EVALUATION.md',lines.join('\n'));console.log('Wrote EVALUATION.md');
